#!/bin/bash

if ! ps -aux | grep -v grep | grep "polybar status"; then
  polybar status
fi

if ! ps -aux | grep -v grep | grep "glava --desktop"; then
  #commented because i havent configured glava yet
  #glava --desktop
fi
